"""
github_client.py — Phase 7: commit the agent's fix to a branch and open a
draft PR via the GitHub REST API.

The high-level entry point is commit_fix_and_open_pr(): it creates a fix branch
from the current working tree (the changes the Phase-5 agent just made), pushes
it, then opens a *draft* PR linked to the Jira ticket. Nothing is auto-merged —
a human reviews and approves.
"""
import os
import time

import requests
from git import Repo
from dotenv import load_dotenv

# Use the OS trust store so requests works behind corporate TLS inspection.
try:
    import truststore
    truststore.inject_into_ssl()
except Exception:  # noqa: BLE001 — optional; falls back to certifi
    pass

load_dotenv()

GITHUB_TOKEN = os.environ.get("GITHUB_TOKEN", "")
GITHUB_OWNER = os.environ.get("GITHUB_OWNER", "")
GITHUB_REPO  = os.environ.get("GITHUB_REPO", "")
GITHUB_BASE_BRANCH = os.environ.get("GITHUB_BASE_BRANCH", "main")
# REST API base. Default = public github.com; for GitHub Enterprise Server set
# GITHUB_API_URL=https://<host>/api/v3 (e.g. https://github.cainc.com/api/v3).
GITHUB_API_URL = os.environ.get("GITHUB_API_URL", "https://api.github.com").rstrip("/")


def commit_and_push(repo_path: str, branch_name: str, commit_message: str) -> None:
    """Creates a branch from the current state, stages all changes, commits, and pushes."""
    repo = Repo(repo_path)
    repo.git.checkout("-b", branch_name)
    repo.git.add("-A")
    repo.index.commit(commit_message)
    origin = repo.remote("origin")
    origin.push(refspec=f"{branch_name}:{branch_name}")


def _pr_body(diagnosis: dict, jira_key: str) -> str:
    if diagnosis.get("fix_applied"):
        test_line = (
            f"**Regression test:** `{diagnosis.get('test_added','(added)')}` — "
            + ("`./mvnw test` passed ✅" if diagnosis.get("test_passed") else "build NOT green ⚠")
            + "\n\n"
        )
    else:
        test_line = "**Note:** diagnosis only — no code change was written.\n\n"
    return (
        "🤖 This PR was auto-generated by AutoFix in response to a production exception.\n\n"
        f"**Linked Jira:** [{jira_key}]({os.environ.get('JIRA_SITE','')}/browse/{jira_key})\n\n"
        f"**Root cause:** {diagnosis['root_cause']}\n\n"
        f"**Fix:** {diagnosis.get('fix_description','')}\n\n"
        + test_line
        + "**Files changed:**\n"
        + "\n".join(f"- `{f}`" for f in diagnosis.get("files_changed", []))
        + f"\n\n**Confidence:** {diagnosis.get('confidence','?')}/5\n\n"
        "**Human review required.** AutoFix does not auto-merge."
    )


def open_draft_pr(diagnosis: dict, jira_key: str, branch_name: str) -> tuple[int, str]:
    """Opens a draft PR for an already-pushed branch and returns (number, url)."""
    title = f"[AutoFix][{jira_key}] Handle missing enrollment for requested academic year"
    resp = requests.post(
        f"{GITHUB_API_URL}/repos/{GITHUB_OWNER}/{GITHUB_REPO}/pulls",
        headers={
            "Authorization": f"Bearer {GITHUB_TOKEN}",
            "Accept": "application/vnd.github+json",
        },
        json={
            "title": title,
            "head": branch_name,
            "base": GITHUB_BASE_BRANCH,
            "body": _pr_body(diagnosis, jira_key),
            "draft": True,
        },
        timeout=15,
    )
    resp.raise_for_status()
    data = resp.json()
    return data["number"], data["html_url"]


def _branch_slug(text: str, max_words: int = 4) -> str:
    """Convert a description to a kebab-case slug of at most max_words words."""
    import re
    words = re.sub(r"[^a-zA-Z0-9\s]", "", text.lower()).split()
    return "-".join(words[:max_words]) or "automated-fix"


def commit_fix_and_open_pr(diagnosis: dict, jira_key: str, repo_path: str) -> tuple[int, str]:
    """Commit the working-tree fix to a new branch, push it, then open the draft PR."""
    short_desc = _branch_slug(diagnosis.get("fix_description", "automated fix"))
    # NOTE: git branch names may not contain '[' or ']' — keep this bracket-free.
    branch_name = f"AutoFix-{jira_key}-{short_desc}"
    commit_message = f"[AutoFix][{jira_key}] {diagnosis.get('fix_description', 'Automated fix')}"
    commit_and_push(repo_path, branch_name, commit_message)
    return open_draft_pr(diagnosis, jira_key, branch_name)
