"""
jira_format.py — the standard AutoFix Jira ticket format (Atlassian Document Format).

AutoFix files every incident as a *structured* ticket so a reviewer can act on it
without re-reading raw logs. `build_description(diagnosis)` returns an ADF doc
with these sections, in order:

  1. Description          — one-paragraph overview of the incident.
  2. Steps to Reproduce   — ordered list of the exact steps that trigger it.
  3. Logs / Stack Trace   — the captured exception/log excerpt (code block, truncated).
  4. Root Cause           — the grounded cause (cites file:line).
  5. Nature of Fix        — what changed + the files touched + the regression test.
  6. Acceptance Criteria  — testable conditions for "done".
  7. Automation Details   — diagnosis source, confidence, build/test status.

The log excerpt comes from the detected incident (diagnosis["log_excerpt"]),
set by claude_agent so the real stack trace lands on the ticket.

Every section degrades gracefully when a field is missing (renders "n/a"
rather than failing), so even a fallback diagnosis yields a valid, well-formed
ticket. `steps_to_reproduce` and `acceptance_criteria` are produced by the
agent (see claude_agent.py); the rest comes from the diagnosis dict.
"""
from __future__ import annotations


def _text(s) -> dict:
    s = str(s).strip() if s is not None else ""
    return {"type": "text", "text": s or "n/a"}


def _para(s) -> dict:
    return {"type": "paragraph", "content": [_text(s)]}


def _heading(s: str, level: int = 3) -> dict:
    return {"type": "heading", "attrs": {"level": level}, "content": [_text(s)]}


def _as_list(value) -> list:
    if value is None:
        return []
    if isinstance(value, str):
        return [value]
    return list(value)


def _list(items, ordered: bool = False) -> dict:
    safe = [str(i).strip() for i in _as_list(items) if str(i).strip()]
    if not safe:
        safe = ["n/a"]
    return {
        "type": "orderedList" if ordered else "bulletList",
        "content": [{"type": "listItem", "content": [_para(i)]} for i in safe],
    }


_MAX_LOG_CHARS = 4000


def _log_block(excerpt) -> dict:
    """A monospaced code block for the log/stack-trace excerpt (truncated, never empty)."""
    text = (str(excerpt).strip() if excerpt else "")
    if not text:
        return _para("n/a")
    if len(text) > _MAX_LOG_CHARS:
        text = text[:_MAX_LOG_CHARS] + "\n… (truncated)"
    return {"type": "codeBlock", "attrs": {"language": "text"},
            "content": [{"type": "text", "text": text}]}


def _build_status(diagnosis: dict) -> str:
    if not diagnosis.get("fix_applied"):
        # diagnose-only run (or fallback): no code change
        return "diagnosis only (no code change)"
    test_passed = diagnosis.get("test_passed", diagnosis.get("tests_passed"))
    if test_passed is True:
        return "fix + regression test applied; build green ✅"
    if test_passed is False:
        return "fix applied; build NOT green ⚠ (needs human review)"
    return "fix applied"


def build_description(diagnosis: dict) -> dict:
    """Build the standard AutoFix ticket description (an ADF doc) from a diagnosis dict."""
    fix_applied = bool(diagnosis.get("fix_applied"))
    overview = (
        "Auto-detected production incident. AutoFix (autonomous incident response) read the "
        "service source to diagnose the root cause, "
        + ("applied a minimal fix with a regression test, " if fix_applied else "")
        + "and opened a draft pull request for human review. Nothing is auto-merged."
    )
    test_added = diagnosis.get("test_added")

    content = [
        _para("🤖 Auto-generated by AutoFix — review the linked PR before merging."),

        _heading("Description"),
        _para(overview),

        _heading("Steps to Reproduce"),
        _list(diagnosis.get("steps_to_reproduce"), ordered=True),

        _heading("Logs / Stack Trace"),
        _log_block(diagnosis.get("log_excerpt")),

        _heading("Root Cause"),
        _para(diagnosis.get("root_cause")),

        _heading("Nature of Fix"),
        _para(diagnosis.get("fix_description")),
        _para("Files changed:"),
        _list(diagnosis.get("files_changed")),

        _heading("Acceptance Criteria"),
        _list(diagnosis.get("acceptance_criteria")),

        _heading("Automation Details"),
        _list([
            f"Diagnosis source: {diagnosis.get('source', 'agent-sdk')}",
            f"Confidence: {diagnosis.get('confidence', '?')}/5",
            f"Build/test: {_build_status(diagnosis)}",
            f"Regression test: {test_added}" if test_added else "Regression test: n/a",
            "PR link: see the linked pull request",
        ]),
    ]
    return {"type": "doc", "version": 1, "content": content}
